---
- name: Close firewall port
  community.windows.win_firewall_rule:
    name: Grafana Alloy Agent
    localport: 12345
    action: allow
    direction: in
    protocol: tcp
    state: absent

- name: Check for uninstall.exe
  ansible.windows.win_stat:
    path: "{{ install_dir }}/Uninstall.exe"
  register: uninstall

- name: Uninstall grafana agent
  when: uninstall.stat.exists
  ansible.windows.win_package:
    path: "{{ install_dir }}/Uninstall.exe"
    product_id: Grafana Alloy
    arguments: /S
    state: absent
  # notify: Reboot

- name: Clean up Grafana Alloy folder
  ansible.windows.win_file:
    path: "{{ install_dir }}"
    state: absent
