---
- name: Install Grafana Alloy
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: true

  tasks:

    - name: Install Grafana Alloy service
      when: task == "install"
      ansible.builtin.include_role:
        name: eingram23.windows.win_grafana_alloy
        tasks_from: install

    - name: Uninstall Grafana Alloy service
      when: task == "uninstall"
      ansible.builtin.include_role:
        name: eingram23.windows.win_grafana_alloy
        tasks_from: uninstall
